manifest = "c6cc9fff1f2ffbc962dc8e15679ad91bd47a48c2ed1286602bcc117e1be9452b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type_index"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.66.0" ]
revision = "8dc91ee53734be8ff8ce63685788490d0ad30b6d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.66.0" ]
revision = "bbc1bc3ec06d91bea9ee8e8e9b900de37998e063"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.66.0" ]
revision = "a7b436f2c55279cb107d854110ae6e8cc7157501"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.66.0" ]
revision = "a7be6c827538ef90c7dba6e10cf00dc14584b75d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.66.0" ]
revision = "06136d7b02f567829df8d287d7bc95158a346f21"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.66.0" ]
revision = "9ef0ad8898e51321477a55e9ec7886db33ae50f3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.66.0" ]
revision = "af98003381e3a79c22e79597ffdf681ed544d83b"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.66.0" ]
revision = "f40e33d9d3096ea6cf213b206be9f8c5ff0fe1ac"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.66.0" ]
revision = "e1dc6ac4af7aeeb5ddb3c9d979531137e0f30816"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.66.0" ]
revision = "33c37eb8f5d57f3e613a0fb345c61e9a8b75300a"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.66.0" ]
revision = "8da0fe673cb6201d150f2d9a78bfa8aec1beeefc"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.66.0" ]
revision = "adc304616726d4abcbb0549f90cc74c2eb71cf26"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.66.0" ]
revision = "13a62020ec56b6e2d11c9ff79a69d38f4d38fd74"
