targets = [ "//:any" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.65.1"
